### PR TITLE
Run enqueue_zero_buffer on the correct CUDA stream

### PR DESCRIPTION
**Pull request by bmerry**
It was running synchronously on the default stream, which could lead to
inefficiencies.

### CODE REVIEW

**Comment by bmerry** [comment]
It looks like fixing the issue that was causing lots more failures on my laptop also fixed the Jenkins unit testing.

**Review by richarms — APPROVED** [review]
adds explicit asynchronous behaviour to pycuda stream for memset operation -- pyopencl handles async zero buffer operations inherently (https://documen.tician.de/pyopencl/runtime_memory.html)

**Comment by richarms** [comment]
> It looks like fixing the issue that was causing lots more failures on my laptop also fixed the Jenkins unit testing.

do you mean the flake8 "noqa F811" or the "command_queue.finish()" fixes? Or both?

**Comment by bmerry** [comment]
> do you mean the flake8 "noqa F811" or the "command_queue.finish()" fixes? Or both?

The latter.

**Pull request merged**
